---

- name: Install python-software-properties
  apt: name=python-software-properties state=present

- name: Install Open JDK
  sudo: yes
  apt: pkg={{item}} state=present
  with_items:
  - openjdk-7-jre
    
- name: Download Graylog repository package
  get_url: url="https://packages.graylog2.org/repo/packages/graylog-1.0-repository-ubuntu14.04_latest.deb" dest=/tmp/graylog_repository.deb

- apt: name=apt-transport-https state=installed

- name: Install Graylog repository
  apt: deb=/tmp/graylog_repository.deb state=installed dpkg_options='force-all'
  register: install_repo

- apt: update_cache=yes
  when: install_repo.changed == True
