#! /bin/sh
### BEGIN INIT INFO
# Provides:          Graylog2
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Graylog2
# Description:       Starts Graylog2 using start-stop-daemon
### END INIT INFO

GL_HOME=/opt/graylog2/server
GL_CTL=$GL_HOME/bin/graylogctl
NAME=graylog2
DESC=graylog2
PID_FILE=/tmp/graylog2.pid
CONFIG_FILE=/etc/graylog/server/server.conf

test -f $GL_CTL || exit 0

set -e

case "$1" in
  start)
    echo -n "Starting $DESC... "
    "$GL_CTL" start -f "$CONFIG_FILE" &
    echo "started (`cat "$PID_FILE"`)."
    ;;
  stop)
    PID=`cat "$PID_FILE"`
    echo -n "Stopping $DESC ($PID)..."
    kill $PID
    echo stopped.
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0