---
- name: check current timezone
  shell: cat /etc/timezone
  register: current_zone
 
- name: Set timezone variables
  copy: content={{my_zone}}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  when: current_zone.stdout != my_zone
  notify: update timezone