---
- name: Install ElasticSearch Ubuntu Source Key
  sudo: yes
  apt_key: state=present url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add ElasticSearch repository into APT
  sudo: yes
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present

- name: Update APT cache
  apt: update_cache=yes
  sudo: yes

- name: Install Open JDK and ElasticSearch
  sudo: yes
  apt: pkg={{item}} state=present
  with_items:
  - openjdk-7-jre
  - elasticsearch
  
- name: Update Elasticsearch configuration
  sudo: yes
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644

- name: Start elasticsearch
  sudo: yes
  service: name={{item}} state=restarted
  with_items:
  - elasticsearch
